[BE/#39] Comment Mapper 구현 완료
codestates-seb/seb40_main_025 pull request #45
Opened 2022-11-17 12:57 UTC by yhwang15

- Comment Mapper 구현 완료
- CommentController Post, Get 요청 기능 보완중

2022-11-17 16:12 UTC, wonkang2 requested changes
Artwork Entity CommentList에 즉시로딩을 한 이유가 궁금합니다..!

2022-11-17 16:12 UTC, wonkang2 commented on server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/entity/Artwork.java
> +    @LazyCollection(LazyCollectionOption.FALSE)
@LazyCollection(LazyCollectionOption.FALSE) - 즉시 로딩을 하시는 이유가 따로 있으신가요??

찾아보니까 이렇게 하면 Artwork가 조회될 때마다 Artwork 조회 쿼리문 + 묶여있는 댓글에 대한 데이터 조회 쿼리문을 날린다고 하는데
artwork쪽에서 댓글 데이터가 필요한 경우는 작품 전체 조회, 개별 조회 할 때만 댓글 데이터(개수)가 필요해서..
지연로딩으로 댓글 관련 메서드를 사용할 때만 조회 쿼리문이 실행되도 좋을 것 같은데 
혹시 다른 이유가 있으시면 말씀해주세요!

https://www.baeldung.com/hibernate-lazycollection

2022-11-18 02:21 UTC, wonkang2 commented on server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/controller/CommentController.java
> +        Artwork artwork = artworkService.findArtwork(artworkId);
findArtwork -> findVerifiedArtwork()메소드로 구현 오늘 중으로 해놓겠습니당

2022-11-18 02:21 UTC, wonkang2 commented on server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/controller/CommentController.java
> +        artwork.addCommentList(comment);
연관관계 매핑에서 추가하는 쪽은 fk를 가지고 있는 주테이블에서 해야 한다고 합니당. 
그러면 artwork.add가 아닌 comment에서 추가하는게 맞다고 생각합니당..

2022-11-18 02:21 UTC, wonkang2 commented on server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/controller/CommentController.java
> +        gallery.addCommentList(comment);
이 부분도 동일하게 주테이블 기준으로 추가하는게 맞다고 생각합니당

2022-11-18 02:21 UTC, wonkang2 commented on server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/controller/CommentController.java
> +                commentMapper.commentToGalleryCommentResponseDtoList(gallery.getCommentList());
CommentRepository.findAllByGallery_GalleryId(long galleryId)로 대체할 수 있어 보입니당

2022-11-18 02:22 UTC, yhwang15 commented on server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/entity/Artwork.java
> +    @LazyCollection(LazyCollectionOption.FALSE)
좋은 지적 감사합니다. N+1 문제 떄문에 떄문에 lazy로 반영하는게 좋을것같습니다.

2022-11-18 07:07 UTC, philE22 approved these changes
수고하셨습니다

2022-11-18 07:21 UTC, wonkang2 approved these changes
고생하셨습니당~

2022-11-18 07:57 UTC, merged