Fe 12/headermockup - 헤더구현, 등록페이지 구현, 모달창구현
codestates-seb/seb40_main_025 pull request #62
Opened 2022-11-18 16:15 UTC by kkdy21

1. 헤더 목업을 만들었습니다.
2. 등록페이지를 구현했습니다.
3. 재사용가능한 모달창 구현했습니다.

### 소개
Modal/components/ModalContiner.ts의 'ModalBackdrop' 컴포넌트가 배경이되는 검은 화면입니다.
Modal/components/ModalContiner.ts의 `Alert`가 삭제, 등록 등 을 물어보는 컴포넌트입니다.

### 사용방법
- 사용하고자 하는 컴포넌트에서 아래와같이 불러와서 사용합니다.
- zustand를 이용한 store의 ModalStore의 state를 불러와서 삼항연산자로 ModalBackdrop / Alert 를 넣어서 구현하면됩니다. - 33번째줄 
(Alert대신 다른 컴포넌트를 넣어도 됩니다.)
<img width="571" alt="스크린샷 2022-11-19 오전 1 04 26" src="https://user-images.githubusercontent.com/86215246/202751092-450f0f65-7a97-4750-9b41-b096c8ed7c6d.png">

-  Alert에는 data를 전달받습니다.  사용하고자 하는 컴포넌트에서 data객체를 만드시고 전달하면 됩니다. data 형식은 지켜줘야하고 onClick에 원하는 로직 넣어서 전달해주면 됩니다.
<img width="568" alt="스크린샷 2022-11-19 오전 1 04 57" src="https://user-images.githubusercontent.com/86215246/202750323-98f2bca8-7eab-4811-8846-d05b5b6fa831.png">

- data에 들어갈수 있는 값은 아래와같이 4가지입니다.
<img width="292" alt="스크린샷 2022-11-19 오전 1 02 24" src="https://user-images.githubusercontent.com/86215246/202755578-5f2d86a6-66d1-460a-a038-423625ff2a9e.png">

### 구현 화면
<img width="448" alt="image" src="https://user-images.githubusercontent.com/86215246/202750772-ce8ee278-2109-4365-9880-3b924467a665.png">
<img width="433" alt="image" src="https://user-images.githubusercontent.com/86215246/202750828-6d1c3558-9f9d-46f6-94d2-bf6daa5f255b.png">

<img width="353" alt="스크린샷 2022-11-19 오전 12 08 59" src="https://user-images.githubusercontent.com/86215246/202750702-9693bd4d-ac1c-4716-90e1-5833a77f2a61.png">
<img width="353" alt="스크린샷 2022-11-19 오전 12 08 54" src="https://user-images.githubusercontent.com/86215246/202750706-3e5eeb3c-93c7-4904-bdce-8c938863723a.png">
<img width="353" alt="스크린샷 2022-11-19 오전 12 08 50" src="https://user-images.githubusercontent.com/86215246/202750709-55d677f5-dde5-434d-8fd0-2795875f0371.png">
<img width="353" alt="스크린샷 2022-11-19 오전 12 08 40" src="https://user-images.githubusercontent.com/86215246/202750712-a7fdf7bf-cfec-4858-ab0f-9b71dc514917.png">

2022-11-18 18:52 UTC, dorrion requested changes
작업하시느라 고생하셨습니다! 코멘트 내용 확인 후 수정하고 다시 언급 주세요..! 바로 리뷰하러 오겠습니당

2022-11-18 18:52 UTC, dorrion commented on client/src/App.tsx
> +import UploadPicture from 'UploadPicture';
App.tsx에서 UploadPicture은 제외하고 올려야 할 것 같습니다!

2022-11-18 18:52 UTC, dorrion commented on client/src/shared/styled/Theme.ts
> +    black_001: '#121111',
저희 prettier.json에서는 tabWidth가 2로 되어있는데, 대연님 문서 서식은 4칸으로 적용되고 있는 것 같습니당! 관련 설정 확인하신 후 문서 서식 적용해주세용 !

2022-11-19 01:33 UTC, kkdy21 commented on client/src/App.tsx
> +import UploadPicture from 'UploadPicture';
확인했습니다~!

2022-11-19 01:33 UTC, kkdy21 commented on client/src/shared/styled/Theme.ts
> +    black_001: '#121111',
"editor.defaultFormatter": "esbenp.prettier-vscode"로 안되어있었네요 확인했습니다~!

2022-11-19 01:46 UTC, kkdy21 commented
> 작업하시느라 고생하셨습니다! 코멘트 내용 확인 후 수정하고 다시 언급 주세요..! 바로 리뷰하러 오겠습니당

수정완료했습니다~ 놓친부분이었는데 감사합니다

2022-11-19 01:48 UTC, Inside-eun approved these changes
고생하셨습니다~

2022-11-19 01:50 UTC, dorrion commented on client/src/shared/styled/Theme.ts
> +    black_002: '#1D1D1D',
혹싀 Theme.ts tap 한 번만 더 확인 가능할까욤?

2022-11-19 01:52 UTC, kkdy21 commented on client/src/shared/styled/Theme.ts
> +    black_002: '#1D1D1D',
> 혹싀 Theme.ts tap 한 번만 더 확인 가능할까욤?

엇 로컬코드에는 2칸으로 되어있는데 커밋한건 4칸이네요 다시 해볼게요 ㅠㅠ

2022-11-19 01:56 UTC, dorrion approved these changes
확인 완료했습니다 고생하셨습니다!

2022-11-19 01:56 UTC, merged