Feat/#47 Comment CRUD 기능구현 완료
codestates-seb/seb40_main_025 pull request #64
Opened 2022-11-18 22:34 UTC by yhwang15

1. Comment CRUD 기능 구현 완료하였습니다. 
2. 전반적인 코드 리팩토링을 진행하였습니다.

2022-11-20 06:55 UTC, philE22 requested changes
리뷰했습니다

2022-11-20 06:55 UTC, philE22 commented on server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/controller/CommentController.java
> +    @PatchMapping("/{gallery-id}/artworks/comments/{comment-id}")
수정이랑 삭제 url이 api명세서 상에는 /galleries/{gallery-id}/comments/{comment-id}인데 이렇게 바뀐 이유가 있을까요?

2022-11-20 06:55 UTC, philE22 commented on server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/service/CommentService.java
> +            givenGallery.orElseThrow(() -> new BusinessLogicException(ExceptionCode.GALLERY_NOT_FOUND));
galleryService.findGallery(Long galleryId) 메서드로 해당 전시회가 존재하는지, 오픈된 전시관인지 검증할 수 있어서 그거 사용하셔도 됩니다.
그리고 갤러리 있는지 검증하는거는 작품댓글이든 전시댓글이든 확인해야하는거라 조건문 밖에 빼도 될거같아요

2022-11-20 06:55 UTC, philE22 commented on server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/service/CommentService.java
> +                throw new BusinessLogicException(ExceptionCode.GALLERY_NOT_FOUND);
이거 전시관은 있는데 댓글이 아직 안달린 경우가 있을테니까 commentPage 가 비어있든 아니든 그냥 보내도 될거같아요.
이러면 전시관에 댓글이 하나도 안달려있을 뿐인데 전시관이 없다는 에러가 날거같네요?
일단 응답으로는 데이터를 보내고, 데이터가 비어있을 때 '댓글이 아직없습니다' 같은 화면 처리는 프론트에서 하는게 좋지 않을까요?

2022-11-20 06:55 UTC, philE22 commented on server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/entity/Comment.java
> +    private CommentStatus commentStatus = CommentStatus.VALID;
commentService.createComment() 에서 VALID set 하니까 여기서 선언 안해줘도될거같네요.

2022-11-20 06:55 UTC, philE22 commented on server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/service/CommentService.java
> +        galleryService.verifiedGalleryExist(memberId);
아 이 메서드는 이미 오픈된 전시가 있으면 전시를 더 못만들게 하는 메서드라 현재는 gallertService.findGallery()를 쓰셔야합니다.
혼란 생기지않게 리팩터링할때 galleryService쪽 메서드들 손보겠습니다.

2022-11-20 07:42 UTC, yhwang15 commented on server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/controller/CommentController.java
> +    @PatchMapping("/{gallery-id}/artworks/comments/{comment-id}")
아마 작성하다가 착오가 있었나봅니다. artworks 만 빼면 될것같습니다.

2022-11-20 07:43 UTC, yhwang15 commented on server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/service/CommentService.java
> +            givenGallery.orElseThrow(() -> new BusinessLogicException(ExceptionCode.GALLERY_NOT_FOUND));
넵 반영하겠습니다

2022-11-20 07:46 UTC, yhwang15 commented on server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/service/CommentService.java
> +                throw new BusinessLogicException(ExceptionCode.GALLERY_NOT_FOUND);
응답으로 데이터를 보내려면 빈 페이지보내면 될까요? 아니면 댓글이 아직없다는 response를 보내는게 나을까요?

2022-11-20 07:49 UTC, philE22 commented on server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/service/CommentService.java
> +                throw new BusinessLogicException(ExceptionCode.GALLERY_NOT_FOUND);
음 저는 개인적으로 빈페이지를 보내도 괜찮을거같다고 생각한건데, 사실 그부분은 프론트 분들이랑 이야기 해보는게 좋을듯합니다.

2022-11-21 03:18 UTC, philE22 approved these changes
수고하셨습니다.

2022-11-21 04:47 UTC, wonkang2 approved these changes
고생하셨습니다.

2022-11-21 04:48 UTC, merged